meta_product_name: "MYGROWBOX"
meta_title: "MYGROWBOX - Vos plantes comme vous ne les avez jamais vues"
meta_description: "MYGROWBOX propose une technologie innovante au service de vos plantes. Gagnez du temps, développez votre expertise et augmentez le rendement de vos plantes grâce à notre solution de suivi en temps réel."
meta_image: "og_image.png"
